server:
  port: 8070

spring:
  application:
    name: modoGateway
  cloud:
    nacos:
      server-addr: http://msapinacos.modo2.cn

    gateway:
      routes:
        - id: modouser
          uri: lb://modoUserServer/
          predicates:
            - Path=/user/**

        - id: modomodule
          uri: lb://modoModule/
          predicates:
            - Path=/module/**
        #            filters:
        #            - StripPrefix=1

        #          - id: projectHelper
        #            uri: http://localhost:8051/
        #            predicates:
        #            - Path=/ph/**
        #            filters:
        #            - StripPrefix=1

        - id: modonotice
          uri: lb://modoModule
          predicates:
            - Path=/notice/**
          filters:
            - StripPrefix=1
          order: 2

        - id: modonoticews
          uri: lb:ws://modoModule
          predicates:
            - Path=/notice/websocket/**
          filters:
            - StripPrefix=1
          order: 1


#          - id: modoversion
#            uri: http://localhost:8110/
#            predicates:
#            - Path=/version/**
#            filters:
#            - StripPrefix=1

