server:
  port: 8091
  servlet:
    context-path: /
logging:
  config: classpath:logback-spring.xml
  level:
    root: info
spring:
  datasource:
      url: jdbc:mysql://localhost:3306/king_of_repository?autoReconnect=true&characterEncoding=utf8&useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      sql-script-encoding: utf-8
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true





